### ISSUE TITLE
could not found the "apo2holo_datasets" directory

### ISSUE THREAD

**Issue by bwang-ecnu** [Zhang-Runze/PackDock#2]
Excellent work! When I installed the relevant environment running "python get_pocket/ get_pocke.py "I encountered the following error：
python get_pocket/get_pocket.py
Traceback (most recent call last):
  File "get_pocket/get_pocket.py", line 114, in <module>
    apolist = pd.read_csv(f"./apo2holo_datasets/{group}.list")
  File "/home/software/Miniconda3/envs/packdock/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 912, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/software/Miniconda3/envs/packdock/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 577, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/software/Miniconda3/envs/packdock/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1407, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/home/software/Miniconda3/envs/packdock/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1661, in _make_engine
    self.handles = get_handle(
  File "/home/software/Miniconda3/envs/packdock/lib/python3.8/site-packages/pandas/io/common.py", line 859, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: './apo2holo_datasets/group3.list'. 
Where can I find the "apo2holo_datasets" folder? Thank you!

**Comment by Zhang-Runze** [comment]
Thank you very much for your interest in PackDock! 
The get_pocket.py is an example. The address for the apo public benchmark dataset is http://huanglab.phys.hust.edu.cn/apo2holo/. Please download or use it according to their requirements. 
If you have any other questions, please contact me in time! Or you can also email me.

**Comment by bwang-ecnu** [comment]
Thank you for your sharing, I will try further！
